### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by Ziome3eg** [Source2ZE/CleanerCS2#14]
Hi, I've tried to compile your plugin but i have problem on both windows 10 and ubuntu 24.04.1 LTS.
I want to recompile it first and next rewrite it for csgo, so I can cleanup console on my servers with regex.
On both machines i cloned hl2sdk branch cs2 from github, and metamod branch 1.12-dev, but on windows i've got problem that xmake is not able to install abseil 

> install abseil 20260107.0 .. failed

on linux it passed but struggles to compile

> 968:13: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  968 |         p = ( void* )GetUnsignedInt();
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-gnu-line-marker’ may have been intended to silence earlier diagnostics
error: /home/kosiu/metamod-source/core/ISmmAPI.h:129:73: error: ‘ConCommandBase’ has not been declared
  129 |                 virtual bool RegisterConCommandBase(ISmmPlugin *plugin, ConCommandBase *pCommand) =0;
      |                                                                         ^~~~~~~~~~~~~~
/home/kosiu/metamod-source/core/ISmmAPI.h:137:75: error: ‘ConCommandBase’ has not been declared
  137 |                 virtual void UnregisterConCommandBase(ISmmPlugin *plugin, ConCommandBase *pCommand) =0;
      |                                                                           ^~~~~~~~~~~~~~
/home/kosiu/metamod-source/core/ISmmPlugin.h:428:66: error: ‘ConCommandBase’ has not been declared
  428 |                 virtual void OnUnlinkConCommandBase(PluginId id, ConCommandBase *pCommand)
      |

Can you help me somehow?

**Comment by Vauff** [comment]
You need to compile with Metamod 2.0 (master branch), SteamRT3 is also recommended.
